# Generated by Django 3.1.12 on 2025-01-29 03:33

import Recipes.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', djongo.models.fields.EmbeddedField(model_container=Recipes.models.Ingredient)),
                ('quantity', models.CharField(max_length=100)),
            ],
        ),
    ]
