# Generated by Django 3.1.12 on 2025-01-29 03:33

import Recipes.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('instructions', models.TextField(default='')),
                ('ingredients', djongo.models.fields.ArrayField(default=list, model_container=Recipes.models.Ingredient)),
            ],
        ),
    ]
