# Generated by Django 3.1.12 on 2025-01-27 21:36

import Recipes.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('instructions', models.TextField(default='')),
                ('ingredients', djongo.models.fields.ArrayField(model_container=Recipes.models.Ingredient)),
            ],
        ),
    ]
