# Generated by Django 3.1.12 on 2025-01-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='RecipeId',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='RecipeImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipes',
            old_name='RecipeName',
            new_name='title',
        ),
        migrations.AddField(
            model_name='recipes',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipes',
            name='instructions',
            field=models.TextField(default=''),
        ),
    ]
